---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-postgres"
spec:
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}