replicaCount: 1
image:
  repository: postgres
  tag: "17.2"
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 5432
resources:
env:
  - name: POSTGRES_DB
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: name
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: user
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: password
volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: postgres-volume-claim
volumeMounts:
  - name: postgres-storage
    mountPath: /var/lib/postgresql/data