// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/tongineers/dice-ton-api/config"
	"github.com/tongineers/dice-ton-api/internal/app/dependencies"
	"github.com/tongineers/dice-ton-api/internal/app/initializers"
	"github.com/tongineers/dice-ton-api/internal/services/tonapi"
)

// Injectors from wire.go:

func BuildApplication() (*Application, error) {
	configConfig := config.LoadConfig()
	apiClient, err := initializers.InitializeTonClient(configConfig)
	if err != nil {
		return nil, err
	}
	logger := initializers.InitializeLogs()
	v := initializers.InitializeTonClientOpts(apiClient, configConfig, logger)
	service, err := tonapi.New(v...)
	if err != nil {
		return nil, err
	}
	container := &dependencies.Container{
		Service: service,
		Config:  configConfig,
		Logger:  logger,
	}
	app, err := initializers.InitializeServer(container)
	if err != nil {
		return nil, err
	}
	application := &Application{
		app:       app,
		container: container,
	}
	return application, nil
}
