info:
  contact: {}
paths:
  /api/v1/transactions:
    get:
      consumes:
      - application/json
      description: get status
      operationId: get-transactions
      parameters:
      - description: Address
        in: path
        name: addr
        required: true
        type: string
      - description: Hash
        in: path
        name: hash
        required: true
        type: string
      - description: Lt
        in: path
        name: lt
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get Transactions from the TON Blockchain
swagger: "2.0"
